CREATE TABLE "market_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" varchar(20),
  "timestamp" timestamp,
  "open" decimal,
  "high" decimal,
  "low" decimal,
  "close" decimal,
  "volume" decimal
);

CREATE TABLE "trades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "symbol" varchar(20),
  "action" varchar(4),
  "quantity" decimal,
  "price" decimal,
  "timestamp" timestamp,
  "strategy_name" varchar(50),
  "order_id" uuid,
  "fees" decimal,
  "status" varchar(10) DEFAULT 'PENDING',
  "execution_time" timestamp,
  "notes" text
);

CREATE TABLE "portfolio_snapshots" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "timestamp" timestamp,
  "symbol" varchar(20),
  "quantity" decimal,
  "price" decimal,
  "value" decimal,
  "cash" decimal,
  "strategy_name" varchar(50)
);

CREATE TABLE "signals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "symbol" varchar(20),
  "signal_type" varchar(10),
  "confidence" decimal,
  "generated_at" timestamp,
  "strategy_name" varchar(50)
);

CREATE TABLE "performance_metrics" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "strategy_name" varchar(50),
  "timestamp" timestamp,
  "pnl" decimal,
  "sharpe_ratio" decimal,
  "drawdown" decimal
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "last_login" timestamp,
  "account_balance" decimal DEFAULT 0,
  "api_key_hash" varchar(255),
  "risk_tolerance" varchar(10) DEFAULT 'MEDIUM',
  "is_active" boolean DEFAULT true,
  "timezone" varchar(50) DEFAULT 'UTC'
);

CREATE TABLE "watchlists" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "symbol" varchar(20) NOT NULL,
  "added_at" timestamp DEFAULT (now())
);

CREATE TABLE "risk_rules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "rule_name" varchar(50) NOT NULL,
  "rule_type" varchar(20) NOT NULL,
  "rule_value" decimal NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "audit_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "action" varchar(50) NOT NULL,
  "details" text,
  "timestamp" timestamp DEFAULT (now()),
  "ip_address" varchar(45)
);

CREATE UNIQUE INDEX ON "market_data" ("symbol", "timestamp");

CREATE INDEX "idx_trades_user_time" ON "trades" ("user_id", "timestamp");

CREATE INDEX "idx_trades_symbol_time" ON "trades" ("symbol", "timestamp");

CREATE INDEX "idx_signals_user_strategy" ON "signals" ("user_id", "strategy_name", "generated_at");

CREATE INDEX "idx_performance_strategy_time" ON "performance_metrics" ("strategy_name", "timestamp");

CREATE UNIQUE INDEX ON "watchlists" ("user_id", "symbol");

COMMENT ON COLUMN "trades"."status" IS 'PENDING, FILLED, CANCELLED';

COMMENT ON COLUMN "trades"."execution_time" IS 'Actual execution time';

COMMENT ON COLUMN "trades"."notes" IS 'Trade reasoning';

COMMENT ON COLUMN "users"."api_key_hash" IS 'Alpaca API key';

COMMENT ON COLUMN "users"."risk_tolerance" IS 'LOW, MEDIUM, HIGH';

ALTER TABLE "trades" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "portfolio_snapshots" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "signals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "watchlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "risk_rules" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
