CREATE TABLE "market_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "symbol" varchar(20),
  "timestamp" timestamp,
  "open" decimal,
  "high" decimal,
  "low" decimal,
  "close" decimal,
  "volume" decimal
);

CREATE TABLE "trades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "symbol" varchar(20),
  "action" varchar(4),
  "quantity" decimal,
  "price" decimal,
  "timestamp" timestamp,
  "strategy_name" varchar(50),
  "order_id" uuid,
  "fees" decimal
);

CREATE TABLE "portfolio_snapshots" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "timestamp" timestamp,
  "symbol" varchar(20),
  "quantity" decimal,
  "price" decimal,
  "value" decimal,
  "cash" decimal,
  "strategy_name" varchar(50)
);

CREATE TABLE "signals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "symbol" varchar(20),
  "signal_type" varchar(10),
  "confidence" decimal,
  "generated_at" timestamp,
  "strategy_name" varchar(50)
);

CREATE TABLE "performance_metrics" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "strategy_name" varchar(50),
  "timestamp" timestamp,
  "pnl" decimal,
  "sharpe_ratio" decimal,
  "drawdown" decimal
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "last_login" timestamp
);

CREATE UNIQUE INDEX ON "market_data" ("symbol", "timestamp");

ALTER TABLE "trades" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "portfolio_snapshots" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "signals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
